<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-E1E9EHH" name="datashare.TestNG_DataStore_ThreadLocal_02" tests="2" failures="0" timestamp="07 Dec 2021 04:41:19 GMT" time="29.568" errors="1">
  <testcase name="createBooking" time="9.556" classname="datashare.TestNG_DataStore_ThreadLocal_02"/>
  <testcase name="retrieveBooking" time="20.012" classname="datashare.TestNG_DataStore_ThreadLocal_02">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at datashare.TestNG_DataStore_ThreadLocal_02.retrieveBooking(TestNG_DataStore_ThreadLocal_02.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- retrieveBooking -->
</testsuite> <!-- datashare.TestNG_DataStore_ThreadLocal_02 -->
